### ISSUE TITLE
Icon in Branding plug-in

### ISSUE THREAD

**Issue by tshoang** [eventB-Soton/ScenarioChecker#10]
The icon for ScenarioChecker in the the branding plug-in seems to be different from the other UML-B features, e.g., Class diagrams. This causes the issues that two icons for UML-B are showing in "About Rodin" dialog.
 Just install ScenarioChecker (0.0.0.release) with any other UML-B features to see the problem.

**Comment by cfsnook** [comment]
This is intended. Scenario Checker has the new icon without the i. 
Scenario Checker is correct and I intend to change all the others to match as part of the re-branding re-issue.

**Comment by cfsnook** [comment]
I have raised issues on all the other UML-B plug ins to update their branding to match this one. Hence closing this issue.
